### ISSUE TITLE
Possible Incompatibility with Sacrificials' Extreme Violence mod (or atleast the latest version maybe, 2.1)

### ISSUE THREAD

**Issue by rfwainug** [ColonolNutty/Sims4CommunityLibrary#9]
[Sims4CommunityLib] 2020-08-30 10:04:29.881637 Traceback (most recent call last):
  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper
  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 209, in c_api_server_tick
  File "sims4communitylib\utils\common_injection_utils.py", line 94, in _wrapped_function
  File "sims4communitylib\exceptions\common_exceptions_handler.py", line 37, in log_exception
  File "sims4communitylib\utils\common_injection_utils.py", line 89, in _wrapped_function
  File "sims4communitylib\events\zone_update\common_zone_update_event_dispatcher.py", line 72, in _common_zone_update
  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v158b\injector.py", line 26, in _wrapped_function
  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v158b\zone_tick.py", line 81, in _turbolib_zone_game_update
  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 486, in update
  File "T:\InGame\Gameplay\Scripts\Server\broadcasters\broadcaster_service.py", line 527, in update
  File "T:\InGame\Gameplay\Scripts\Server\broadcasters\broadcaster_service.py", line 601, in _update
  File "T:\InGame\Gameplay\Scripts\Server\broadcasters\broadcaster.py", line 507, in apply_broadcaster_effect
  File "T:\InGame\Gameplay\Scripts\Server\broadcasters\broadcaster_effect.py", line 89, in apply_broadcaster_effect
  File "T:\InGame\Gameplay\Scripts\Server\broadcasters\broadcaster_effect.py", line 170, in _should_apply_broadcaster_effect
  File "T:\InGame\Gameplay\Scripts\Server\broadcasters\broadcaster_effect.py", line 138, in _should_apply_broadcaster_effect
  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 470, in run_tests
  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 104, in __call__
AttributeError: 'NoneType' object has no attribute 'expected_kwargs'
Error occurred while injecting into function '_common_zone_update' of class -> AttributeError: 'NoneType' object has no attribute 'expected_kwargs

**Comment by ColonolNutty** [comment]
It isn't an incompatibility, their mod is simply throwing an error :)
